// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";

// Load environment file based on parameter or default to .env.local
dotenv.config({ 
  path: process.env.ENV_FILE ?? ".env.local" 
});

// Overriding Database URL to use localhost. In .env.local, it is set to the docker container.

// When running local use this
// const databaseUrl = process.env.DATABASE_URL_LOCALHOST ?? env("DATABASE_URL");  

const databaseUrl = env("DATABASE_URL");  

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
